### PR TITLE
First commit of react port

### PR DESCRIPTION
**Pull request by geramirez**
@kiranjthomas moved over some parts to react.

### CODE REVIEW

**Comment by geramirez** [comment]
image


image


image

**Comment by geramirez** [comment]
I've added Heroku pipelines when it's merged to main, it should deploy.

**Comment by kiranjthomas** [comment]
Very cool! I looked through the pipeline documentation and it seems like it takes a lot of burden off of devs. Neat.

re: persistent storage - I'm planning to use Postgres. Heroku doesn't appear to offer a free MongDB or NoSQL add-on. https://elements.heroku.com/addons. If we use Postgres, it looks like the Review App will launch a separate Postgres instance from the production Postgres. Does that seem right to you?

**Comment by geramirez** [comment]
Yes, Postgres makes sense. I think it's okey if a separate one is deployed. There will just have to be way to run a setup or migrations.

**Pull request merged**
